version: '3'
services:
  django:
    container_name: docker-django
    build: ./covid_tracer_local
    volumes:
      - ./covid_tracer_local:/project
    ports:
      - 8081:8000
    depends_on:
      - db

  nginx:
    container_name: docker-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./covid_tracer_local/media:/usr/share/nginx/media
      - ./covid_tracer_local/static:/usr/share/nginx/static
    ports:
      - 8006:8080
    depends_on:
      - django


  db:
    container_name: docker-db
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7620
      MYSQL_DATABASE: covid_tracer_local
    ports:
      - 3302:3306
volumes:
  mysql_data:


  
