# Generated by Django 3.0.7 on 2020-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gen_id', models.IntegerField()),
                ('app_gen_id', models.IntegerField()),
                ('pers_num', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_num', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
