# Generated by Django 3.0.7 on 2020-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persinfo',
            name='app_gen_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='user_gen_id',
            field=models.CharField(max_length=20),
        ),
    ]
