# Generated by Django 3.0.7 on 2020-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20200611_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persinfo',
            name='app_gen_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='pers_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='user_gen_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='persinfo',
            unique_together={('user_gen_id', 'app_gen_id')},
        ),
    ]
