# Generated by Django 3.0.7 on 2020-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20200616_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persinfo',
            name='app_gen_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='persinfo',
            name='user_gen_id',
            field=models.CharField(max_length=12),
        ),
    ]
